zuul:
  routes:
    account-service:
      path: api/account/**
      serviceId: account-service

server:
  port: 8111

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: routes,filters
  endpoint:
    routes:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
